### ISSUE TITLE
[QUESTION] phpunit

### ISSUE THREAD

**Issue by amadeu01** [mayronceccon/desafios-grupo-estudos-php#1]
Cara, quando fui rodar o phpunit no desafio do ano bissexto, ele deu que não achava a classe do ano bissexto.
Mas, quando rodei 
```bash
$ /vendor/bin/phpunit test/
```
Funcionou.

Minha pergunta é, como eu faço para rodar o `phpunit` no diretorio pricipal, sem ter que falar que eu quero rodar os testes da pasta `x`?

Eu até adicionei no composer.json

```json
 "autoload-dev" : {
        "psr-4" : {
            "TEST\\" : "test/"
        }
    },
```

Adicionei isso para tentar rodar só com `phpunit` no diretorio raiz do projeto que eu tava (No caso `ano_bissexto/`)

**Comment by mayronceccon** [comment]
@amadeu01 pode criar um arquivo phpunit.xml, neste arquivo são inseridas todas configurações referentes a execução dos testes.

Assim basta somente executar o comando do phpunit.

Atualizei o repo com esse arquivo.

**Comment by amadeu01** [comment]
Valeu @mayronceccon 

Não sabia que tinha que ter o phpunit.xml hehe!
Obrigado!

**Comment by mayronceccon** [comment]
A principio não é necessário, mas ai o phpunit tem que rodar passando os parâmetros diretamente na linha de comando.
